---
# tasks file for ./roles/dns_server

- name: Install bind9
  apt:
    name: 
      - bind9
      - bind9utils
      - bind9-doc
    state: present

- name: Allow DNS UDP
  ansible.builtin.iptables:
    chain: INPUT
    protocol: udp
    destination_port: 53
    jump: ACCEPT

- name: Allow DNS TCP
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 53
    jump: ACCEPT

- name: Copy named.conf.local
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: restart bind9

- name: Create zone file
  template:
    src: db.technova.pt.j2
    dest: /etc/bind/db.technova.pt
  notify: restart bind9

- name: Ensure BIND options are set
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: restart bind9