---
# handlers file for roles/ldap
- name: Restart slapd
  service:
    name: slapd
    state: restarted

- name: Restart Nginx
  service:
    name: nginx
    state: restarted

- name: Update CA certificates
  command: update-ca-certificates