# Control node 
[control_nodes]
auto ansible_host=192.168.10.30

# Managed nodes
[managed_nodes]
infra ansible_host=192.168.10.10
app ansible_host=192.168.10.20
monitor ansible_host=192.168.10.40

# Shared variables for all nodes
[all:vars]
ansible_port=22
ansible_user=vagrant
ansible_ssh_private_key_file=/home/vagrant/.ssh/ansible_auto_ed25519