---
- name: Webserver Setup
  hosts: app
  become: yes
  
  tasks:
    - name: Ensure apt cache is updated
      apt:
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - docker
    
    # Database container must be created first because 
    # it creates the network used by the web server
    - mysql_container

    - phpmyadmin_container
        
    - nginx_container