- hosts: all
  become: true
  serial: 1
  roles:
    - common
    - sysadmin
    - operator
    - security
    - firewall
    - backup

- hosts: infra
  become: true
  roles:
    - ldap
    - samba  
